### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by lzygitk7** [ZYChen33/ML-assisted-amidase-catalytic-enantioselectivity-prediction-and-rational-design#1]
Thank you for your work. Are there any released pre-trained models for this project?

**Comment by ZYChen33** [comment]
For information about the models and hyperparameters used in this project, you can refer to the main text and SI in [https://doi.org/10.1038/s41467-024-53048-0](https://doi.org/10.1038/s41467-024-53048-0). The GitHub repository includes the Random Forest model used in this work, along with the code for generating descriptors. Thank you for your interest in our work.
